server:
  port: 8080
application:
  name: RestApps
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:C:/Users/mateu/Desktop/mateusz desktop/rest/rest-db
  jpa:
    hibernate:
      ddl-auto: create
      generate-ddl: true
      open-in-view: false

